@host = localhost:3033
@cuit = CUIT_CONTRIBUYENTE

###
# Obtiene la descripcion del WS
POST http://{{host}}/afip_rest/descr/ws_sr_constancia_inscripcion HTTP/1.1
content-type: application/json

###
# Obtiene la descripcion de un metodo en particular 
POST http://{{host}}/afip_rest/descr/ws_sr_constancia_inscripcion/getPersona HTTP/1.1
content-type: application/json

###
# Metodo de autenticacion para obtener el ticket de acceso 
# es llamado automaticamente cuando este no existe o es muy viejo
POST http://{{host}}/afip_rest/wsaa/{{cuit}}/ws_sr_constancia_inscripcion HTTP/1.1
content-type: application/json

###
# Llama al metodo getPersona
POST http://{{host}}/afip_rest/call/{{cuit}}/ws_sr_constancia_inscripcion/getPersona HTTP/1.1
content-type: application/json

{
    "token": "",
    "sign": "",
    "cuitRepresentada": "{{cuit}}",
    "idPersona": ""
}
